### ISSUE TITLE
"make" encounter error

### ISSUE THREAD

**Issue by luckypoem** [danielinux/dohd#1]
hi.

yudeMacBook-Air:~ brite$ git clone https://github.com/danielinux/dohd
yudeMacBook-Air:~ brite$ cd dohd
yudeMacBook-Air:dohd brite$ make
cc -O3 -Wall -Wextra -Wno-sign-compare   -c -o dohd.o dohd.c
cc -O3 -Wall -Wextra -Wno-sign-compare   -c -o libevquick.o libevquick.c
libevquick.c:82:5: error: unknown type name 'timer_t'; did you mean 'time_t'?
    timer_t timer_id;
    ^~~~~~~
    time_t
/usr/include/sys/_types/_time_t.h:30:26: note: 'time_t' declared here
typedef __darwin_time_t         time_t; 
                                ^
libevquick.c:93:5: warning: implicit declaration of function 'timer_create' is invalid in
      C99 [-Wimplicit-function-declaration]
    timer_create(CLOCK_REALTIME, &evp, &ctx->timer_id);
    ^
libevquick.c:98:29: error: variable has incomplete type 'const struct itimerspec'
    const struct itimerspec ival = { {0, 0} , {interval / 1000, (interval % 1000) ...
                            ^
libevquick.c:98:18: note: forward declaration of 'struct itimerspec'
    const struct itimerspec ival = { {0, 0} , {interval / 1000, (interval % 1000) ...
                 ^
libevquick.c:99:5: warning: implicit declaration of function 'timer_settime' is invalid in
      C99 [-Wimplicit-function-declaration]
    timer_settime(ctx->timer_id, 0, &ival, NULL);
    ^
2 warnings and 2 errors generated.
make: *** [libevquick.o] Error 1
yudeMacBook-Air:dohd brite$

how to fix them?

**Comment by danielinux** [comment]
Sorry, this was never tested on MacOS. If you know how to fix it and have the hardware to test it, I'll be happy to accept a PR. Does it make sense to run a bind server on a Mac anyway?

**Comment by danielinux** [comment]
no response, this daemon will be linux-only for now.
